In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("recipes.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1090 entries, 0 to 1089
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    1090 non-null   int64
 1   recipe_name   1090 non-null   object
 2   prep_time     1039 non-null   object
 3   cook_time     782 non-null    object
 4   total_time    1045 non-null   object
 5   servings      1090 non-null   int64
 6   yield         879 non-null    object
 7   ingredients   1090 non-null   object
 8   directions    1090 non-null   object
 9   rating        1090 non-null   float64
 10  url           1090 non-null   object
 11  cuisine_path  1090 non-null   object
 12  nutrition     1090 non-null   object
 13  timing        1090 non-null   object
 14  img_src       1090 non-null   object
dtypes: float64(1), int64(2), object(12)
memory usage: 127.9+ KB

In [4]:
df.head()

,Unnamed: 0,recipe_name,prep_time,cook_time,total_time,servings,yield,ingredients,directions,rating,url,cuisine_path,nutrition,timing,img_src
0,0,Apple-Cranberry Crostada,NaN,NaN,NaN,8,6 to 8 - servings,"3 tablespoons butter, 2 pounds Granny Smith ap...",Heat butter in a large skillet over medium-hig...,4.4,https://www.allrecipes.com/recipe/76931/apple-...,/Desserts/Fruit Desserts/Apple Dessert Recipes/,"Total Fat 18g 23%, Saturated Fat 7g 34%, Chole...","Servings: 8, Yield: 6 to 8 - servings",https://www.allrecipes.com/thmb/Tf1wH73bfH6Oql...
1,1,Apple Pie by Grandma Ople,30 mins,1 hrs,1 hrs 30 mins,8,1 9-inch pie,"8 small Granny Smith apples, or as needed, ½ c...","Peel and core apples, then thinly slice. Set a...",4.8,https://www.allrecipes.com/recipe/12682/apple-...,/Desserts/Pies/Apple Pie Recipes/,"Total Fat 19g 24%, Saturated Fat 9g 46%, Chole...","Prep Time: 30 mins, Cook Time: 1 hrs, Total Ti...",https://www.allrecipes.com/thmb/1I95oiTGz6aEpu...
2,2,Sarah's Homemade Applesauce,10 mins,15 mins,25 mins,4,NaN,"4 apples - peeled, cored and chopped, ¾ cup w...","Combine apples, water, sugar, and cinnamon in ...",4.8,https://www.allrecipes.com/recipe/51301/sarahs...,/Side Dish/Applesauce Recipes/,"Total Fat 0g 0%, Sodium 3mg 0%, Total Carbohyd...","Prep Time: 10 mins, Cook Time: 15 mins, Total ...",https://www.allrecipes.com/thmb/VY5d0tZHB8xz6y...
3,3,Apple Crisp,30 mins,45 mins,1 hrs 15 mins,12,1 9x13-inch pan,"10 cups all-purpose apples, peeled, cored and ...",Preheat the oven to 350 degrees F (175 degrees...,4.7,https://www.allrecipes.com/recipe/12409/apple-...,/Desserts/Crisps and Crumbles Recipes/Apple Cr...,"Total Fat 8g 11%, Saturated Fat 5g 25%, Choles...","Prep Time: 30 mins, Cook Time: 45 mins, Total ...",https://www.allrecipes.com/thmb/uAzhPOh86PfR-N...
4,4,Apple Pie Filling,20 mins,20 mins,2 hrs 40 mins,40,5 9-inch pies,"18 cups thinly sliced apples, 3 tablespoons le...",Toss apples with lemon juice in a large bowl a...,4.7,https://www.allrecipes.com/recipe/12681/apple-...,/Desserts/Pies/Apple Pie Recipes/,"Total Fat 0g 0%, Sodium 61mg 3%, Total Carbohy...","Prep Time: 20 mins, Cook Time: 20 mins, Additi...",https://www.allrecipes.com/thmb/c0bbYaS1V_mTt_...

In [5]:
import pandas as pd
import numpy as np

# Definimos el rango de 2 meses
fecha_inicio = pd.to_datetime('2026-05-01')
fecha_fin = pd.to_datetime('2026-06-30')

# Calculamos la cantidad de días en el intervalo
dias_rango = (fecha_fin - fecha_inicio).days

# Generamos un offset aleatorio de días para cada una de las 1090 filas
# np.random.randint generará valores entre 0 y 60
offsets_aleatorios = np.random.randint(0, dias_rango + 1, size=len(df))

# Creamos la columna de fecha
df['date'] = fecha_inicio + pd.to_timedelta(offsets_aleatorios, unit='D')

# Ordenamos por fecha para mantener la estructura de serie de tiempo
df = df.sort_values('date').reset_index(drop=True)

# Verificamos la distribución
print(df['date'].value_counts().head()) # Ver cuántas recetas cayeron por día

date
2026-05-23    27
2026-05-24    25
2026-06-21    24
2026-05-13    24
2026-05-10    23
Name: count, dtype: int64

In [6]:
df.head()

,Unnamed: 0,recipe_name,prep_time,cook_time,total_time,servings,yield,ingredients,directions,rating,url,cuisine_path,nutrition,timing,img_src,date
0,594,Fruit and Yogurt Smoothie,5 mins,NaN,5 mins,2,NaN,"1 cup strawberries, 1 banana, ½ cup yogurt, ¼...","Combine strawberries, banana, yogurt, pineappl...",4.7,https://www.allrecipes.com/recipe/215189/fruit...,/Drinks Recipes/Smoothie Recipes/Strawberry/,"Total Fat 1g 2%, Saturated Fat 1g 4%, Choleste...","Prep Time: 5 mins, Total Time: 5 mins, Serving...",https://www.allrecipes.com/thmb/nXTnAdimMBtkQi...,2026-05-01
1,229,"Orange, Fig, and Gorgonzola Salad",15 mins,NaN,15 mins,4,4 servings,"2 heads romaine lettuce, chopped, 2 oranges -...","Combine lettuce, oranges, Gorgonzola cheese, a...",4.7,https://www.allrecipes.com/recipe/234219/orang...,/Salad/Fruit Salad Recipes/Orange Salad Recipes/,"Total Fat 7g 8%, Saturated Fat 4g 19%, Cholest...","Prep Time: 15 mins, Total Time: 15 mins, Servi...",https://www.allrecipes.com/thmb/_qqHaDK6ZWLhH1...,2026-05-01
2,935,Fresh Fruit Basket Cobbler,20 mins,20 mins,1 hrs,8,1 8x13-inch dish,"2 cups sliced fresh peaches, 2 cups sliced fre...",Preheat oven to 350 degrees F (175 degrees C)....,4.5,https://www.allrecipes.com/recipe/215149/fresh...,/Desserts/Fruit Desserts/Peach Dessert Recipes/,"Total Fat 8g 10%, Saturated Fat 2g 10%, Choles...","Prep Time: 20 mins, Cook Time: 20 mins, Additi...",https://www.allrecipes.com/thmb/M2HlzlgXhGsLA1...,2026-05-01
3,81,Caramel Apples,8 mins,2 mins,25 mins,6,6 caramel apples,"6 apples, 6 wooden craft sticks, cooking s...",Remove the stem from each apple and press a cr...,4.4,https://www.allrecipes.com/recipe/21130/carame...,/Desserts/Specialty Dessert Recipes/Caramel Ap...,"Total Fat 6g 7%, Saturated Fat 2g 9%, Choleste...","Prep Time: 8 mins, Cook Time: 2 mins, Addition...",https://www.allrecipes.com/thmb/Gc2LqawZpqaCSW...,2026-05-01
4,975,Sweet Coconut Rice,5 mins,20 mins,25 mins,4,4 servings,"1 ½ cups long-grain white rice, 1 (14 ounce) c...","Stir rice, coconut milk, and water together in...",4.5,https://www.allrecipes.com/recipe/237021/sweet...,/Side Dish/Rice Side Dish Recipes/,"Total Fat 22g 28%, Saturated Fat 19g 95%, Sodi...","Prep Time: 5 mins, Cook Time: 20 mins, Total T...",https://www.allrecipes.com/thmb/3LmVEctbWeHFsr...,2026-05-01

In [ ]:
# Eliminamos la columna 'Unnamed: 0' si existe (a veces aparece al guardar CSVs)
df = df.drop(columns=['Unnamed: 0'], errors='ignore')

In [ ]:
# Guardamos el nuevo CSV con la columna de fecha
df.to_csv('recetas.csv', index=False)